export const BOUNTY_ITEMS = [
    {
        id: "f1",
        name: "Black Backpack",
        imgSrc: "/bountyItems/BlackBackpack.png",
        description: "16 inch x 13 inch",
        color: "Blue",
        category: "Clothing",
        price: 21.0,
        location: "2nd floor",
        date: "Nov.4",
        claimCode: "1234",
    },
    {
        id: "f2",
        name: "Red Mug",
        imgSrc: "/bountyItems/RedMug.png",
        description: "500ml",
        color: "Blue",
        category: "Clothing",
        price: 20.0,
        location: "1st floor",
        date: "Nov.5",
        claimCode: "1234",
    },
    {
        id: "f3",
        name: "Blue Waterbottle",
        imgSrc: "/bountyItems/BlueWaterbottle.png",
        description: "500 ml, silver bottle cap",
        color: "Blue",
        category: "Clothing",
        price: 19.0,
        location: "3rd floor",
        date: "Nov.5",
        claimCode: "1234",
    },
    {
        id: "f4",
        name: "Silver Smartphone",
        imgSrc: "/bountyItems/SilverSmartphone.png",
        description: "iPhone 7 ",
        color: "Blue",
        category: "Clothing",
        price: 19.0,
        location: "parking lot",
        date: "Nov.6",
        claimCode: "1234",
    },
    {
        id: "l5",
        name: "BlackGlasses",
        imgSrc: "/bountyItems/BlackGlasses.png",
        description: "Black glasses with silver decoration",
        color: "Blue",
        category: "Clothing",
        price: 15.0,
        location: "2nd floor",
        date: "Nov.6",
        claimCode: "1234",
    },
];
