export const BOUNTY_ITEMS = [
    {
        name: "Black Backpack",
        imgSrc: "/bountyItems/BlackBackpack.png",
        description: "16 inch x 13 inch",
        price: 21.0,
        color: 'Black',
        category: 'Cloth',
    },
    {
        name: "Red Mug",
        imgSrc: "/bountyItems/RedMug.png",
        description: "500ml",
        price: 20.0,
        color: 'Red',
        category: 'Bottles',
    },
    {
        name: "Blue Waterbottle",
        imgSrc: "/bountyItems/BlueWaterbottle.png",
        description: "500 ml, silver bottle cap",
        price: 19.0,
        color: 'Blue',
        category: 'Bottles',
    },
    {
        name: "Silver Smartphone",
        imgSrc: "/bountyItems/SilverSmartphone.png",
        description: "iPhone 7 ",
        price: 19.0,
        color: 'White',
        category: 'Phone',
    },
    {
        name: "BlackGlasses",
        imgSrc: "/bountyItems/BlackGlasses.png",
        description: "Black glasses with silver decoration",
        price: 15.0,
        color: 'black',
        category: 'Cloth',
    },
];
