export const BOUNTY_ITEMS = [
    {
        id: "1",
        name: "Black Backpack",
        imgSrc: "/bountyItems/BlackBackpack.png",
        description: "16 inch x 13 inch",
        price: 21.0,
        location: "2nd floor",
        date: "Nov.4",
    },
    {
        id: "2",
        name: "Red Mug",
        imgSrc: "/bountyItems/RedMug.png",
        description: "500ml",
        price: 20.0,
        location: "1st floor",
        date: "Nov.5",
    },
    {
        id: "3",
        name: "Blue Waterbottle",
        imgSrc: "/bountyItems/BlueWaterbottle.png",
        description: "500 ml, silver bottle cap",
        price: 19.0,
        location: "3rd floor",
        date: "Nov.5",
    },
    {
        id: "4",
        name: "Silver Smartphone",
        imgSrc: "/bountyItems/SilverSmartphone.png",
        description: "iPhone 7 ",
        price: 19.0,
        location: "parking lot",
        date: "Nov.6",
    },
    {
        id: "5",
        name: "BlackGlasses",
        imgSrc: "/bountyItems/BlackGlasses.png",
        description: "Black glasses with silver decoration",
        price: 15.0,
        location: "2nd floor",
        date: "Nov.6",
    },
];
